import { createContext, useContext, useState, useEffect } from "react";
import type { ReactNode } from "react";

type Language = 'ru' | 'tj';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Переводы
const translations = {
  ru: {
    // Общие
    'app.name': 'Протокол',
    'app.tagline': 'Система управления задачами',
    'common.loading': 'Загрузка...',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.create': 'Создать',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.all': 'Все',
    'common.yes': 'Да',
    'common.no': 'Нет',
    
    // Навигация
    'nav.dashboard': 'Панель управления',
    'nav.tasks': 'Задачи',
    'nav.my_tasks': 'Мои задачи',
    'nav.all_tasks': 'Все задачи',
    'nav.manager_tasks': 'Задачи менеджера',
    'nav.important_tasks': 'Важные задачи',
    'nav.completed_tasks': 'Выполненные задачи',
    'nav.analytics': 'Аналитика',
    'nav.members': 'Участники',
    'nav.admin_chat': 'Админ чат',
    'nav.profile': 'Профиль',
    'nav.settings': 'Настройки',
    'nav.logout': 'Выйти',
    
    // Задачи
    'tasks.create_task': 'Создать задачу',
    'tasks.task_title': 'Название задачи',
    'tasks.task_description': 'Описание задачи',
    'tasks.task_status': 'Статус',
    'tasks.task_priority': 'Приоритет',
    'tasks.task_assignees': 'Исполнители',
    'tasks.task_manager': 'Ответственный менеджер',
    'tasks.due_date': 'Срок выполнения',
    'tasks.no_tasks': 'Нет задач',
    'tasks.task_created': 'Задача создана',
    'tasks.task_updated': 'Задача обновлена',
    'tasks.task_deleted': 'Задача удалена',
    'tasks.create_new_task': 'Создать новую задачу',
    'tasks.task_name': 'Название',
    'tasks.task_desc': 'Описание',
    'tasks.enter_task_name': 'Введите название задачи',
    'tasks.enter_task_desc': 'Введите описание задачи',
    'tasks.select_status': 'Выберите статус',
    'tasks.select_priority': 'Выберите приоритет',
    'tasks.select_date': 'Выберите дату',
    'tasks.select_manager': 'Выберите ответственного менеджера',
    'tasks.not_assigned': 'Не назначен',
    'tasks.assign_to': 'Ответственный исполнитель',
    'tasks.assign_participant': 'Назначить участника',
    'tasks.select_members': 'Выберите ответственного исполнителя',
    'tasks.select_participant': 'Выберите участника',
    'tasks.selected_count': 'Выбрано исполнителей: {count}',
    'tasks.selected_participants_count': 'Выбрано участников: {count}',
    'tasks.creating': 'Создание...',
    'tasks.create': 'Создать задачу',
    'tasks.cancel': 'Отмена',
    'tasks.admin': 'Админ',
    'tasks.manager': 'Менеджер',
    'tasks.member': 'Исполнитель',
    'tasks.multi_task': 'Создать несколько задач',
    'tasks.multi_task_desc': 'Создайте несколько задач с одним названием',
    'tasks.task_number': 'Задача #{number}',
    'tasks.add_task': 'Добавить еще задачу',
    'tasks.remove_task': 'Удалить',
    'tasks.min_tasks_required': 'Необходимо минимум 2 задачи',
    
    // Статусы
    'status.todo': 'К выполнению',
    'status.in_progress': 'В процессе',
    'status.review': 'На проверке',
    'status.done': 'Выполнено',
    'status.cancelled': 'Отменен',

    // Приоритеты
    'priority.low': 'Низкий',
    'priority.medium': 'Средний',
    'priority.high': 'Высокий',
    
    // Роли
    'role.admin': 'Админ',
    'role.manager': 'Менеджер',
    'role.member': 'Участник',
    'role.super_admin': 'Супер админ',
    
    // Ответы и комментарии
    'responses.title': 'Ответы',
    'responses.add_response': 'Добавить ответ',
    'responses.send_response': 'Отправить ответ',
    'responses.no_responses': 'Нет ответов',
    'responses.attach_file': 'Прикрепить файл',
    'responses.voice_message': 'Голосовое сообщение',
    
    'comments.title': 'Комментарии',
    'comments.add_comment': 'Добавить комментарий',
    'comments.send_comment': 'Отправить комментарий',
    'comments.no_comments': 'Нет комментариев',
    
    // Файлы
    'files.download': 'Скачать',
    'files.preview': 'Просмотр',
    'files.upload': 'Загрузить файл',
    'files.uploading': 'Загрузка...',
    
    // Уведомления
    'notifications.task_assigned': 'Вам назначена новая задача',
    'notifications.task_completed': 'Задача выполнена',
    'notifications.new_comment': 'Новый комментарий',
    'notifications.new_response': 'Новый ответ',
    
    // Общие фразы
    'common.created': 'Создано',
    'tasks.no_tasks_yet': 'У вас пока нет задач',
    'common.loading_data': 'Загрузка данных...',
    
    // Статистика и панель управления
    'dashboard.total_tasks': 'Всего задач',
    'dashboard.in_progress': 'В процессе',
    'dashboard.completed': 'Выполнено',
    'dashboard.overdue': 'Просрочено',
    'dashboard.recent_tasks': 'Последние задачи',
    'dashboard.statistics': 'Статистика',
    'dashboard.overview': 'Обзор',
    
    // Действия с задачами
    'tasks.mark_important': 'Отметить как важное',
    'tasks.unmark_important': 'Убрать из важных',
    'tasks.edit_assignees': 'Редактировать исполнителей',
    'tasks.watch': 'Следить',
    'tasks.unwatch': 'Не следить',
    'tasks.important_tasks': 'Важные задачи',
    
    // Важные задачи страница
    'important_tasks.title': 'Важные задачи',
    'important_tasks.description': 'Задачи, отмеченные администраторами как важные',
    'important_tasks.no_access': 'У вас нет доступа к этой странице. Только супер админы могут просматривать важные задачи.',
    'important_tasks.no_tasks_title': 'Нет важных задач',
    'important_tasks.no_tasks_description': 'Пока нет задач, отмеченных как важные',
    'important_tasks.marked_important': 'Отмечено как важное',
    'important_tasks.by_admin': 'администратором',
    'important_tasks.assignees': 'исполнителей',
    'important_tasks.assignee': 'исполнитель',
    'important_tasks.manager': 'Менеджер:',
    'important_tasks.not_specified': 'Не указан',
    
    // Участники
    'members.remove_member': 'Удалить участника',
    'members.confirm_remove': 'Вы уверены, что хотите удалить этого участника?',
    'members.member_removed': 'Участник удален',
    
    // Сортировка и фильтрация
    'sort.oldest_first': 'Сначала старые',
    'sort.newest_first': 'Сначала новые',
    'filter.filter': 'Фильтр',
    'filter.filter_tasks': 'Фильтровать задачи',
    'filter.all_tasks': 'Все задачи',
    'filter.high_priority': 'Высокий приоритет',
    'filter.archived': 'В архиве',
    'search.find_tasks': 'Найти задачи...',
    'tabs.list': 'Список',
    'tabs.board': 'Доска',
    'tasks.assigned_to_you': 'назначенных вам задач',
    'tasks.no_matching_tasks': 'Задач, соответствующих вашим критериям, не найдено.',
    'tasks.due_date_short': 'Срок',
    'tasks.modified': 'Изменено',
    'tasks.completed_badge': 'Завершено',
    'tasks.no_tasks_in_progress': 'Нет задач в процессе',
    'tasks.no_completed_tasks': 'Нет выполненных задач',
    
    // Все задачи страница
    'all_tasks.title': 'Все задачи',
    'all_tasks.description': 'Управление всеми задачами в организациях',
    'all_tasks.access_denied': 'Доступ запрещен',
    'all_tasks.no_access_message': 'У вас нет прав для просмотра всех задач. Обратитесь к администратору.',
    'all_tasks.loading': 'Загрузка задач...',
    'all_tasks.filters_search': 'Фильтры и поиск',
    'all_tasks.search_placeholder': 'Поиск по названию или описанию...',
    'all_tasks.all_statuses': 'Все статусы',
    'all_tasks.all_priorities': 'Все приоритеты',
    'all_tasks.time_filter': 'Фильтр по времени создания',
    'all_tasks.period': 'Период',
    'all_tasks.all_time': 'Все время',
    'all_tasks.today': 'За сегодня',
    'all_tasks.week': 'За неделю',
    'all_tasks.month': 'За месяц',
    'all_tasks.six_months': 'За 6 месяцев',
    'all_tasks.year': 'За год',
    'all_tasks.custom_period': 'Произвольный период',
    'all_tasks.date_from': 'Дата от',
    'all_tasks.date_to': 'Дата до',
    'all_tasks.reset_period': 'Сбросить период',
    'all_tasks.sort_by': 'Сортировать по',
    'all_tasks.sort_created': 'Дате создания',
    'all_tasks.sort_title': 'Названию',
    'all_tasks.sort_status': 'Статусу',
    'all_tasks.sort_priority': 'Приоритету',
    'all_tasks.sort_due_date': 'Сроку выполнения',
    'all_tasks.statistics_period': 'Статистика',
    'all_tasks.for_period': 'За период',
    'all_tasks.total_tasks': 'Всего задач',
    'all_tasks.from_total': 'из {total} всего',
    'all_tasks.high_priority': 'Высокий приоритет',
    'all_tasks.table_number': '#',
    'all_tasks.table_title': 'Название',
    'all_tasks.table_status': 'Статус',
    'all_tasks.table_priority': 'Приоритет',
    'all_tasks.table_assigned': 'Назначено',
    'all_tasks.table_due_date': 'Срок',
    'all_tasks.table_created': 'Создано',
    'all_tasks.table_actions': 'Действия',
    'all_tasks.not_assigned': 'Не назначено',
    'all_tasks.not_specified': 'Не указан',
    'all_tasks.tasks_count': 'Задачи ({filtered} из {total})',
    'all_tasks.no_tasks_found': 'Задач, соответствующих критериям, не найдено',
    'all_tasks.group_by_title': 'Группировать по названию',
    'all_tasks.groups_count': 'Группы: {groups} ({tasks} задач)',
    'all_tasks.tasks_in_group': '{count} задач в группе',
    'all_tasks.expand_all': 'Развернуть все',
    'all_tasks.collapse_all': 'Свернуть все',
    'all_tasks.view_task': 'Просмотр задачи',
    'all_tasks.view_responses': 'Просмотр ответов',

    // Менеджерские задачи
    'manager_tasks.title': 'Мои задачи как ответственного менеджера',
    'manager_tasks.description': 'Задачи, где вы назначены ответственным менеджером',
    'manager_tasks.no_access': 'У вас нет доступа к этой странице',
    'manager_tasks.no_tasks_title': 'Нет задач как ответственного менеджера',
    'manager_tasks.no_tasks_description': 'У вас пока нет задач, где вы назначены ответственным менеджером',
    'manager_tasks.assignees_count': '{count} исполнителей',
    
    // Аналитика
    'analytics.title': 'Аналитика',
    'analytics.description': 'Статистика и аналитика по задачам',
    'analytics.access_denied': 'Доступ запрещен',
    'analytics.no_access_message': 'У вас нет прав для просмотра аналитики. Обратитесь к администратору.',
    'analytics.loading': 'Загрузка аналитики...',
    'analytics.filters': 'Фильтры',
    'analytics.time_period': 'Период времени',
    'analytics.member': 'Участник',
    'analytics.all_members': 'Все участники',
    'analytics.last_day': 'Последний день',
    'analytics.last_7_days': 'Последние 7 дней',
    'analytics.last_month': 'Последний месяц',
    'analytics.last_6_months': 'Последние 6 месяцев',
    'analytics.last_year': 'Последний год',
    'analytics.total_tasks': 'Всего задач',
    'analytics.completed': 'Выполнено',
    'analytics.in_progress': 'В процессе',
    'analytics.overdue': 'Просрочено',
    'analytics.for_selected_period': 'За выбранный период',
    'analytics.completion_rate': 'Процент выполнения: {rate}%',
    'analytics.active_tasks': 'Активные задачи',
    'analytics.require_attention': 'Требуют внимания',
    'analytics.status_distribution': 'Распределение по статусам',
    'analytics.status_distribution_desc': 'Общее количество задач по статусам',
    'analytics.priority_distribution': 'Распределение по приоритетам',
    'analytics.priority_distribution_desc': 'Общее количество задач по приоритетам',
    'analytics.member_tasks': 'Задачи участника: {name}',
    'analytics.total_tasks_count': 'Всего задач: {count}',
    'analytics.detailed_stats': 'Детальная статистика',
    'analytics.percentage_ratio': 'Процентное соотношение задач',
    'analytics.member_stats': 'Статистика по участникам',
    'analytics.member_stats_desc': 'Количество задач на каждого участника',
    'analytics.activity_timeline': 'Активность за период',
    'analytics.activity_timeline_desc': 'Создание и выполнение задач по времени',
    'analytics.created': 'Создано',
    'analytics.completed_tasks': 'Выполнено',
    'analytics.tasks_count_suffix': 'задач',
    'analytics.chart_title': 'Диаграмма - Vazifa',
    'analytics.chart_analytics': 'Аналитика Vazifa',
    
    // Tech Admin
    'tech_admin.title': 'Панель технического администратора',
    'tech_admin.subtitle': 'Мониторинг системы и технические операции',
    'tech_admin.load_error': 'Ошибка загрузки данных. Попробуйте обновить страницу.',

    // Статистика
    'tech_admin.total_users': 'Всего пользователей',
    'tech_admin.active_users': 'активных за 30 дней',
    'tech_admin.new_today': 'новых сегодня',
    'tech_admin.tasks': 'Задачи',
    'tech_admin.completed': 'выполнено',
    'tech_admin.completion_rate': 'процент выполнения',
    'tech_admin.sms_delivery': 'Доставка SMS',
    'tech_admin.failed': 'ошибок',
    'tech_admin.delivery_rate': 'процент доставки',
    'tech_admin.system_status': 'Статус системы',
    'tech_admin.online': 'В сети',
    'tech_admin.offline': 'Не в сети',
    'tech_admin.uptime': 'Время работы',
    'tech_admin.environment': 'Окружение',
    'tech_admin.today': 'сегодня',

    // Пользователи по ролям
    'tech_admin.users_by_role': 'Пользователи по ролям',
    'tech_admin.role_distribution': 'Распределение ролей',

    // SMPP статус
    'tech_admin.smpp_status': 'Статус SMPP',
    'tech_admin.sms_gateway': 'SMS шлюз',
    'tech_admin.connection': 'Соединение',
    'tech_admin.connected': 'Подключен',
    'tech_admin.disconnected': 'Отключен',
    'tech_admin.reconnect_attempts': 'Попытки переподключения',
    'tech_admin.sms_today': 'SMS сегодня',

    // Быстрые ссылки
    'tech_admin.user_management': 'Управление пользователями',
    'tech_admin.user_management_desc': 'Просмотр и управление пользователями',
    'tech_admin.sms_logs': 'SMS логи',
    'tech_admin.sms_logs_desc': 'Мониторинг доставки и аналитика SMS',
    'tech_admin.email_logs': 'Email логи',
    'tech_admin.email_logs_desc': 'Мониторинг доставки и аналитика Email',
    'tech_admin.queue_management': 'Управление очередью',
    'tech_admin.queue_management_desc': 'Управление очередью SMS задач',
    'tech_admin.audit_logs': 'Журнал аудита',
    'tech_admin.audit_logs_desc': 'Отслеживание действий администраторов',
    'tech_admin.settings': 'Настройки',
    'tech_admin.settings_desc': 'Конфигурация системных настроек',
    'tech_admin.system_health': 'Здоровье системы',
    'tech_admin.system_health_desc': 'Метрики сервера и мониторинг',

    // Страница пользователей
    'tech_admin.users.title': 'Управление пользователями',
    'tech_admin.users.subtitle': 'Просмотр и управление всеми пользователями системы',
    'tech_admin.users.search': 'Поиск по имени, email или телефону...',
    'tech_admin.users.all_roles': 'Все роли',
    'tech_admin.users.all_statuses': 'Все статусы',
    'tech_admin.users.active': 'Активные',
    'tech_admin.users.disabled': 'Отключенные',
    'tech_admin.users.create': 'Создать пользователя',
    'tech_admin.users.name': 'Имя',
    'tech_admin.users.email': 'Email',
    'tech_admin.users.phone': 'Телефон',
    'tech_admin.users.role': 'Роль',
    'tech_admin.users.status': 'Статус',
    'tech_admin.users.last_login': 'Последний вход',
    'tech_admin.users.created': 'Создан',
    'tech_admin.users.actions': 'Действия',
    'tech_admin.users.edit': 'Редактировать',
    'tech_admin.users.reset_password': 'Сбросить пароль',
    'tech_admin.users.disable': 'Отключить',
    'tech_admin.users.enable': 'Включить',
    'tech_admin.users.delete': 'Удалить',
    'tech_admin.users.never': 'Никогда',
    'tech_admin.users.no_users': 'Пользователи не найдены',
    'tech_admin.users.loading': 'Загрузка пользователей...',
    'tech_admin.users.total': 'Всего',
    'tech_admin.users.page': 'Страница',
    'tech_admin.users.of': 'из',
    'tech_admin.users.prev': 'Назад',
    'tech_admin.users.next': 'Вперед',

    // Создание/редактирование пользователя
    'tech_admin.users.create_title': 'Создать пользователя',
    'tech_admin.users.edit_title': 'Редактировать пользователя',
    'tech_admin.users.name_placeholder': 'Введите имя',
    'tech_admin.users.email_placeholder': 'Введите email',
    'tech_admin.users.phone_placeholder': 'Введите телефон',
    'tech_admin.users.password': 'Пароль',
    'tech_admin.users.password_placeholder': 'Введите пароль',
    'tech_admin.users.select_role': 'Выберите роль',
    'tech_admin.users.creating': 'Создание...',
    'tech_admin.users.saving': 'Сохранение...',
    'tech_admin.users.save': 'Сохранить',
    'tech_admin.users.cancel': 'Отмена',

    // Сброс пароля
    'tech_admin.users.reset_password_title': 'Сброс пароля',
    'tech_admin.users.new_password': 'Новый пароль',
    'tech_admin.users.new_password_placeholder': 'Введите новый пароль',
    'tech_admin.users.send_notification': 'Отправить SMS уведомление',
    'tech_admin.users.resetting': 'Сброс...',
    'tech_admin.users.reset': 'Сбросить пароль',

    // Отключение пользователя
    'tech_admin.users.disable_title': 'Отключить пользователя',
    'tech_admin.users.disable_confirm': 'Вы уверены, что хотите отключить этого пользователя?',
    'tech_admin.users.reason': 'Причина',
    'tech_admin.users.reason_placeholder': 'Введите причину',
    'tech_admin.users.disabling': 'Отключение...',

    // Удаление пользователя
    'tech_admin.users.delete_title': 'Удалить пользователя',
    'tech_admin.users.delete_confirm': 'Вы уверены, что хотите удалить этого пользователя? Это действие необратимо.',
    'tech_admin.users.deleting': 'Удаление...',

    // SMS логи
    'tech_admin.sms.title': 'SMS логи',
    'tech_admin.sms.subtitle': 'Мониторинг отправки SMS и аналитика',
    'tech_admin.sms.search': 'Поиск по номеру телефона...',
    'tech_admin.sms.all_statuses': 'Все статусы',
    'tech_admin.sms.sent': 'Отправлено',
    'tech_admin.sms.pending': 'Ожидание',
    'tech_admin.sms.all_types': 'Все типы',
    'tech_admin.sms.phone': 'Телефон',
    'tech_admin.sms.message': 'Сообщение',
    'tech_admin.sms.type': 'Тип',
    'tech_admin.sms.status': 'Статус',
    'tech_admin.sms.date': 'Дата',
    'tech_admin.sms.actions': 'Действия',
    'tech_admin.sms.resend': 'Переотправить',
    'tech_admin.sms.no_logs': 'SMS логи не найдены',
    'tech_admin.sms.loading': 'Загрузка SMS логов...',
    'tech_admin.sms.total': 'Всего SMS',
    'tech_admin.sms.delivery_stats': 'Статистика доставки',
    'tech_admin.sms.error': 'Ошибка',
    'tech_admin.sms.otp': 'OTP код',
    'tech_admin.sms.password_reset': 'Сброс пароля',
    'tech_admin.sms.task_notification': 'Уведомление о задаче',
    'tech_admin.sms.general': 'Общее',

    // Email логи
    'tech_admin.email.title': 'Email логи',
    'tech_admin.email.subtitle': 'Мониторинг отправки Email и аналитика',
    'tech_admin.email.search': 'Поиск по email...',
    'tech_admin.email.recipient': 'Получатель',
    'tech_admin.email.subject': 'Тема',
    'tech_admin.email.type': 'Тип',
    'tech_admin.email.status': 'Статус',
    'tech_admin.email.date': 'Дата',
    'tech_admin.email.actions': 'Действия',
    'tech_admin.email.resend': 'Переотправить',
    'tech_admin.email.no_logs': 'Email логи не найдены',
    'tech_admin.email.loading': 'Загрузка Email логов...',
    'tech_admin.email.total': 'Всего Email',
    'tech_admin.email.delivery_stats': 'Статистика доставки',

    // Очередь
    'tech_admin.queue.title': 'Управление очередью',
    'tech_admin.queue.subtitle': 'Мониторинг и управление очередью SMS задач',
    'tech_admin.queue.waiting': 'Ожидание',
    'tech_admin.queue.active': 'Активные',
    'tech_admin.queue.completed': 'Завершенные',
    'tech_admin.queue.failed': 'Ошибки',
    'tech_admin.queue.delayed': 'Отложенные',
    'tech_admin.queue.paused': 'Приостановлено',
    'tech_admin.queue.running': 'Работает',
    'tech_admin.queue.pause': 'Приостановить',
    'tech_admin.queue.resume': 'Возобновить',
    'tech_admin.queue.clean': 'Очистить старые',
    'tech_admin.queue.job_id': 'ID задачи',
    'tech_admin.queue.job_name': 'Название',
    'tech_admin.queue.job_data': 'Данные',
    'tech_admin.queue.job_status': 'Статус',
    'tech_admin.queue.job_attempts': 'Попытки',
    'tech_admin.queue.job_created': 'Создано',
    'tech_admin.queue.job_actions': 'Действия',
    'tech_admin.queue.retry': 'Повторить',
    'tech_admin.queue.remove': 'Удалить',
    'tech_admin.queue.no_jobs': 'Задачи не найдены',
    'tech_admin.queue.loading': 'Загрузка очереди...',
    'tech_admin.queue.stats': 'Статистика очереди',

    // Аудит логи
    'tech_admin.audit.title': 'Журнал аудита',
    'tech_admin.audit.subtitle': 'Отслеживание всех действий администраторов',
    'tech_admin.audit.search': 'Поиск по описанию...',
    'tech_admin.audit.all_actions': 'Все действия',
    'tech_admin.audit.all_categories': 'Все категории',
    'tech_admin.audit.actor': 'Пользователь',
    'tech_admin.audit.action': 'Действие',
    'tech_admin.audit.category': 'Категория',
    'tech_admin.audit.target': 'Объект',
    'tech_admin.audit.description': 'Описание',
    'tech_admin.audit.ip': 'IP адрес',
    'tech_admin.audit.date': 'Дата',
    'tech_admin.audit.status': 'Статус',
    'tech_admin.audit.success': 'Успешно',
    'tech_admin.audit.error': 'Ошибка',
    'tech_admin.audit.details': 'Детали',
    'tech_admin.audit.no_logs': 'Записи аудита не найдены',
    'tech_admin.audit.loading': 'Загрузка журнала аудита...',
    'tech_admin.audit.user': 'Пользователь',
    'tech_admin.audit.task': 'Задача',
    'tech_admin.audit.system': 'Система',
    'tech_admin.audit.sms': 'SMS',
    'tech_admin.audit.email': 'Email',

    // Настройки
    'tech_admin.settings.title': 'Системные настройки',
    'tech_admin.settings.subtitle': 'Конфигурация параметров системы',
    'tech_admin.settings.sms_settings': 'Настройки SMS',
    'tech_admin.settings.email_settings': 'Настройки Email',
    'tech_admin.settings.notification_settings': 'Настройки уведомлений',
    'tech_admin.settings.maintenance': 'Режим обслуживания',
    'tech_admin.settings.security': 'Безопасность',
    'tech_admin.settings.enabled': 'Включено',
    'tech_admin.settings.disabled': 'Выключено',
    'tech_admin.settings.retry_attempts': 'Количество попыток',
    'tech_admin.settings.retry_delay': 'Задержка между попытками (мс)',
    'tech_admin.settings.daily_limit': 'Дневной лимит',
    'tech_admin.settings.task_assignment': 'Назначение задачи',
    'tech_admin.settings.task_completion': 'Завершение задачи',
    'tech_admin.settings.task_reminder': 'Напоминание о задаче',
    'tech_admin.settings.password_reset': 'Сброс пароля',
    'tech_admin.settings.maintenance_mode': 'Режим обслуживания',
    'tech_admin.settings.maintenance_message': 'Сообщение обслуживания',
    'tech_admin.settings.max_login_attempts': 'Максимум попыток входа',
    'tech_admin.settings.lockout_duration': 'Длительность блокировки (мин)',
    'tech_admin.settings.session_timeout': 'Таймаут сессии (мин)',
    'tech_admin.settings.two_factor': 'Двухфакторная аутентификация',
    'tech_admin.settings.save': 'Сохранить настройки',
    'tech_admin.settings.saving': 'Сохранение...',
    'tech_admin.settings.saved': 'Настройки сохранены',
    'tech_admin.settings.loading': 'Загрузка настроек...',

    // Система
    'tech_admin.system.title': 'Здоровье системы',
    'tech_admin.system.subtitle': 'Мониторинг состояния сервера и сервисов',
    'tech_admin.system.server': 'Сервер',
    'tech_admin.system.server_uptime': 'Время работы',
    'tech_admin.system.server_version': 'Версия Node.js',
    'tech_admin.system.server_platform': 'Платформа',
    'tech_admin.system.server_arch': 'Архитектура',
    'tech_admin.system.database': 'База данных',
    'tech_admin.system.db_status': 'Статус',
    'tech_admin.system.db_response': 'Время отклика',
    'tech_admin.system.smpp': 'SMPP шлюз',
    'tech_admin.system.smpp_status': 'Статус',
    'tech_admin.system.smpp_host': 'Хост',
    'tech_admin.system.smpp_port': 'Порт',
    'tech_admin.system.smpp_reconnect': 'Переподключить',
    'tech_admin.system.memory': 'Память',
    'tech_admin.system.memory_total': 'Всего',
    'tech_admin.system.memory_free': 'Свободно',
    'tech_admin.system.memory_used': 'Использовано',
    'tech_admin.system.cpu': 'Процессор',
    'tech_admin.system.cpu_cores': 'Ядра',
    'tech_admin.system.cpu_model': 'Модель',
    'tech_admin.system.cpu_load': 'Загрузка',
    'tech_admin.system.process': 'Процесс',
    'tech_admin.system.heap_used': 'Heap использовано',
    'tech_admin.system.heap_total': 'Heap всего',
    'tech_admin.system.rss': 'RSS',
    'tech_admin.system.collections': 'Коллекции БД',
    'tech_admin.system.collection_name': 'Название',
    'tech_admin.system.collection_docs': 'Документы',
    'tech_admin.system.collection_size': 'Размер',
    'tech_admin.system.collection_indexes': 'Индексы',
    'tech_admin.system.loading': 'Загрузка данных системы...',
    'tech_admin.system.refresh': 'Обновить',
    'tech_admin.system.reconnecting': 'Переподключение...',
    'tech_admin.system.ms': 'мс',

    // Ошибки
    'errors.generic': 'Произошла ошибка',
    'errors.network': 'Ошибка сети',
    'errors.unauthorized': 'Нет доступа',
    'errors.not_found': 'Не найдено',
  },
  tj: {
    // Общие
    'app.name': 'Протокол',
    'app.tagline': 'Системаи идоракунии вазифаҳо',
    'common.loading': 'Бор шуда истодааст...',
    'common.save': 'Захира кардан',
    'common.cancel': 'Бекор кардан',
    'common.delete': 'Нест кардан',
    'common.edit': 'Таҳрир кардан',
    'common.create': 'Эҷод кардан',
    'common.search': 'Ҷустуҷӯ',
    'common.filter': 'Филтр',
    'common.all': 'Ҳама',
    'common.yes': 'Ҳа',
    'common.no': 'Не',
    
    // Навигация
    'nav.dashboard': 'Лавҳаи идоракунӣ',
    'nav.tasks': 'Вазифаҳо',
    'nav.my_tasks': 'Вазифаҳои ман',
    'nav.all_tasks': 'Ҳамаи вазифаҳо',
    'nav.manager_tasks': 'Вазифаҳои менеҷер',
    'nav.important_tasks': 'Вазифаҳои муҳим',
    'nav.completed_tasks': 'Вазифаҳои иҷрошуда',
    'nav.analytics': 'Таҳлилот',
    'nav.members': 'Иштирокчиён',
    'nav.admin_chat': 'Чати маъмур',
    'nav.profile': 'Профил',
    'nav.settings': 'Танзимот',
    'nav.logout': 'Баромадан',
    
    // Задачи
    'tasks.create_task': 'Вазифа эҷод кардан',
    'tasks.task_title': 'Номи вазифа',
    'tasks.task_description': 'Тавсифи вазифа',
    'tasks.task_status': 'Ҳолат',
    'tasks.task_priority': 'Аввалият',
    'tasks.task_assignees': 'Иҷрокунандагон',
    'tasks.task_manager': 'Менеҷери масъул',
    'tasks.due_date': 'Мӯҳлати иҷро',
    'tasks.no_tasks': 'Вазифаҳо нестанд',
    'tasks.task_created': 'Вазифа эҷод шуд',
    'tasks.task_updated': 'Вазифа навсозӣ шуд',
    'tasks.task_deleted': 'Вазифа нест шуд',
    'tasks.create_new_task': 'Вазифаи нав эҷод кардан',
    'tasks.task_name': 'Ном',
    'tasks.task_desc': 'Тавсиф',
    'tasks.enter_task_name': 'Номи вазифаро ворид кунед',
    'tasks.enter_task_desc': 'Тавсифи вазифаро ворид кунед',
    'tasks.select_status': 'Ҳолатро интихоб кунед',
    'tasks.select_priority': 'Аввалиятро интихоб кунед',
    'tasks.select_date': 'Санаро интихоб кунед',
    'tasks.select_manager': 'Менеҷери масъулро интихоб кунед',
    'tasks.not_assigned': 'Таъин нашуда',
    'tasks.assign_to': 'Иҷрокунандаи масъул',
    'tasks.assign_participant': 'Иштирокчиро таъин кунед',
    'tasks.select_members': 'Иҷрокунандаи масъулро интихоб кунед',
    'tasks.select_participant': 'Иштирокчиро интихоб кунед',
    'tasks.selected_count': 'Иҷрокунандагон интихобшуда: {count}',
    'tasks.selected_participants_count': 'Иштирокчиён интихобшуда: {count}',
    'tasks.creating': 'Эҷод шуда истодааст...',
    'tasks.create': 'Вазифа эҷод кардан',
    'tasks.cancel': 'Бекор кардан',
    'tasks.admin': 'Админ',
    'tasks.manager': 'Менеҷер',
    'tasks.member': 'Иҷрокунанда',
    'tasks.multi_task': 'Як қатор вазифаҳо эҷод кардан',
    'tasks.multi_task_desc': 'Бо як номи умумӣ як қатор вазифаҳо эҷод кунед',
    'tasks.task_number': 'Вазифа №{number}',
    'tasks.add_task': 'Вазифаи навро илова кунед',
    'tasks.remove_task': 'Нест кардан',
    'tasks.min_tasks_required': 'Ҳадди ақал 2 вазифа зарур аст',
    
    // Статусы
    'status.todo': 'Барои иҷро',
    'status.in_progress': 'Дар ҷараён',
    'status.review': 'Дар баррасӣ',
    'status.done': 'Иҷрошуда',
    'status.cancelled': 'Бекоршуда',

    // Приоритеты
    'priority.low': 'Паст',
    'priority.medium': 'Миёна',
    'priority.high': 'Баланд',
    
    // Роли
    'role.admin': 'Админ',
    'role.manager': 'Менеҷер',
    'role.member': 'Иштирокчӣ',
    'role.super_admin': 'Супер админ',
    
    // Ответы и комментарии
    'responses.title': 'Ҷавобҳо',
    'responses.add_response': 'Ҷавоб илова кардан',
    'responses.send_response': 'Ҷавоб фиристодан',
    'responses.no_responses': 'Ҷавобҳо нестанд',
    'responses.attach_file': 'Файл замима кардан',
    'responses.voice_message': 'Паёми овозӣ',
    
    'comments.title': 'Шарҳҳо',
    'comments.add_comment': 'Шарҳ илова кардан',
    'comments.send_comment': 'Шарҳ фиристодан',
    'comments.no_comments': 'Шарҳҳо нестанд',
    
    // Файлы
    'files.download': 'Боргирӣ кардан',
    'files.preview': 'Пешнамоиш',
    'files.upload': 'Файл боркардан',
    'files.uploading': 'Бор шуда истодааст...',
    
    // Уведомления
    'notifications.task_assigned': 'Ба шумо вазифаи нав таъин шуд',
    'notifications.task_completed': 'Вазифа иҷро шуд',
    'notifications.new_comment': 'Шарҳи нав',
    'notifications.new_response': 'Ҷавоби нав',
    
    // Общие фразы
    'common.created': 'Эҷодшуда',
    'tasks.no_tasks_yet': 'Шумо то ҳол вазифаҳо надоред',
    'common.loading_data': 'Маълумот бор шуда истодааст...',
    
    // Статистика и панель управления
    'dashboard.total_tasks': 'Ҳамаи вазифаҳо',
    'dashboard.in_progress': 'Дар ҷараён',
    'dashboard.completed': 'Иҷрошуда',
    'dashboard.overdue': 'Мӯҳлат гузашта',
    'dashboard.recent_tasks': 'Вазифаҳои охирин',
    'dashboard.statistics': 'Омор',
    'dashboard.overview': 'Умумӣ',
    
    // Действия с задачами
    'tasks.mark_important': 'Ҳамчун муҳим қайд кардан',
    'tasks.unmark_important': 'Аз муҳимҳо хориҷ кардан',
    'tasks.edit_assignees': 'Иҷрокунандагонро таҳрир кардан',
    'tasks.watch': 'Назорат кардан',
    'tasks.unwatch': 'Назорат накардан',
    'tasks.important_tasks': 'Вазифаҳои муҳим',
    
    // Важные задачи страница
    'important_tasks.title': 'Вазифаҳои муҳим',
    'important_tasks.description': 'Вазифаҳое, ки маъмурон ҳамчун муҳим қайд кардаанд',
    'important_tasks.no_access': 'Шумо ба ин саҳифа дастрасӣ надоред. Танҳо супер маъмурон метавонанд вазифаҳои муҳимро бубинанд.',
    'important_tasks.no_tasks_title': 'Вазифаҳои муҳим нестанд',
    'important_tasks.no_tasks_description': 'То ҳол вазифаҳое, ки ҳамчун муҳим қайд шуда бошанд, нестанд',
    'important_tasks.marked_important': 'Ҳамчун муҳим қайд шуда',
    'important_tasks.by_admin': 'маъмур',
    'important_tasks.assignees': 'иҷрокунандагон',
    'important_tasks.assignee': 'иҷрокунанда',
    'important_tasks.manager': 'Менеҷер:',
    'important_tasks.not_specified': 'Муайян нашуда',
    
    // Участники
    'members.remove_member': 'Иштирокчиро хориҷ кардан',
    'members.confirm_remove': 'Шумо мутмаин ҳастед, ки мехоҳед ин иштирокчиро хориҷ кунед?',
    'members.member_removed': 'Иштирокчӣ хориҷ карда шуд',
    
    // Сортировка и фильтрация
    'sort.oldest_first': 'Аввал кӯҳнаҳо',
    'sort.newest_first': 'Аввал навҳо',
    'filter.filter': 'Филтр',
    'filter.filter_tasks': 'Вазифаҳоро филтр кардан',
    'filter.all_tasks': 'Ҳамаи вазифаҳо',
    'filter.high_priority': 'Аввалияти баланд',
    'filter.archived': 'Дар бойгонӣ',
    'search.find_tasks': 'Вазифаҳоро ёфтан...',
    'tabs.list': 'Рӯйхат',
    'tabs.board': 'Тахта',
    'tasks.assigned_to_you': 'ба шумо таъин шудаанд',
    'tasks.no_matching_tasks': 'Вазифаҳое, ки ба меъёрҳои шумо мувофиқ мебошанд, ёфт нашуданд.',
    'tasks.due_date_short': 'Мӯҳлат',
    'tasks.modified': 'Тағйир ёфта',
    'tasks.completed_badge': 'Анҷомёфта',
    'tasks.no_tasks_in_progress': 'Вазифаҳо дар ҷараён нестанд',
    'tasks.no_completed_tasks': 'Вазифаҳои анҷомёфта нестанд',
    
    // Все задачи страница
    'all_tasks.title': 'Ҳамаи вазифаҳо',
    'all_tasks.description': 'Идоракунии ҳамаи вазифаҳо дар ташкилотҳо',
    'all_tasks.access_denied': 'Дастрасӣ манъ аст',
    'all_tasks.no_access_message': 'Шумо ҳуқуқи дидани ҳамаи вазифаҳоро надоред. Ба маъмур муроҷиат кунед.',
    'all_tasks.loading': 'Вазифаҳо бор шуда истодаанд...',
    'all_tasks.filters_search': 'Филтрҳо ва ҷустуҷӯ',
    'all_tasks.search_placeholder': 'Ҷустуҷӯ аз рӯи ном ё тавсиф...',
    'all_tasks.all_statuses': 'Ҳамаи ҳолатҳо',
    'all_tasks.all_priorities': 'Ҳамаи аввалиятҳо',
    'all_tasks.time_filter': 'Филтр аз рӯи вақти эҷод',
    'all_tasks.period': 'Давра',
    'all_tasks.all_time': 'Ҳамаи вақт',
    'all_tasks.today': 'Барои имрӯз',
    'all_tasks.week': 'Барои ҳафта',
    'all_tasks.month': 'Барои моҳ',
    'all_tasks.six_months': 'Барои 6 моҳ',
    'all_tasks.year': 'Барои сол',
    'all_tasks.custom_period': 'Давраи дилхоҳ',
    'all_tasks.date_from': 'Аз сана',
    'all_tasks.date_to': 'То сана',
    'all_tasks.reset_period': 'Давраро бекор кардан',
    'all_tasks.sort_by': 'Мураттаб кардан аз рӯи',
    'all_tasks.sort_created': 'Санаи эҷод',
    'all_tasks.sort_title': 'Ном',
    'all_tasks.sort_status': 'Ҳолат',
    'all_tasks.sort_priority': 'Аввалият',
    'all_tasks.sort_due_date': 'Мӯҳлати иҷро',
    'all_tasks.statistics_period': 'Омор',
    'all_tasks.for_period': 'Барои давра',
    'all_tasks.total_tasks': 'Ҳамаи вазифаҳо',
    'all_tasks.from_total': 'аз {total} умуман',
    'all_tasks.high_priority': 'Аввалияти баланд',
    'all_tasks.table_number': '№',
    'all_tasks.table_title': 'Ном',
    'all_tasks.table_status': 'Ҳолат',
    'all_tasks.table_priority': 'Аввалият',
    'all_tasks.table_assigned': 'Таъин шуда',
    'all_tasks.table_due_date': 'Мӯҳлат',
    'all_tasks.table_created': 'Эҷодшуда',
    'all_tasks.table_actions': 'Амалҳо',
    'all_tasks.not_assigned': 'Таъин нашуда',
    'all_tasks.not_specified': 'Муайян нашуда',
    'all_tasks.tasks_count': 'Вазифаҳо ({filtered} аз {total})',
    'all_tasks.no_tasks_found': 'Вазифаҳое, ки ба меъёрҳо мувофиқ мебошанд, ёфт нашуданд',
    'all_tasks.group_by_title': 'Гурӯҳбандӣ аз рӯи ном',
    'all_tasks.groups_count': 'Гурӯҳҳо: {groups} ({tasks} вазифа)',
    'all_tasks.tasks_in_group': '{count} вазифа дар гурӯҳ',
    'all_tasks.expand_all': 'Ҳамаро кушодан',
    'all_tasks.collapse_all': 'Ҳамаро пӯшидан',
    'all_tasks.view_task': 'Дидани вазифа',
    'all_tasks.view_responses': 'Дидани ҷавобҳо',

    // Менеджерские задачи
    'manager_tasks.title': 'Вазифаҳои ман ҳамчун менеҷери масъул',
    'manager_tasks.description': 'Вазифаҳое, ки шумо ҳамчун менеҷери масъул таъин шудаед',
    'manager_tasks.no_access': 'Шумо ба ин саҳифа дастрасӣ надоред',
    'manager_tasks.no_tasks_title': 'Вазифаҳо ҳамчун менеҷери масъул нестанд',
    'manager_tasks.no_tasks_description': 'Шумо то ҳол вазифаҳое надоред, ки дар онҳо ҳамчун менеҷери масъул таъин шуда бошед',
    'manager_tasks.assignees_count': '{count} иҷрокунанда',
    
    // Аналитика
    'analytics.title': 'Таҳлилот',
    'analytics.description': 'Омор ва таҳлилоти вазифаҳо',
    'analytics.access_denied': 'Дастрасӣ манъ аст',
    'analytics.no_access_message': 'Шумо ҳуқуқи дидани таҳлилотро надоред. Ба маъмур муроҷиат кунед.',
    'analytics.loading': 'Таҳлилот бор шуда истодааст...',
    'analytics.filters': 'Филтрҳо',
    'analytics.time_period': 'Давраи вақт',
    'analytics.member': 'Иштирокчӣ',
    'analytics.all_members': 'Ҳамаи иштирокчиён',
    'analytics.last_day': 'Рӯзи охирин',
    'analytics.last_7_days': 'Охирин 7 рӯз',
    'analytics.last_month': 'Моҳи охирин',
    'analytics.last_6_months': 'Охирин 6 моҳ',
    'analytics.last_year': 'Соли охирин',
    'analytics.total_tasks': 'Ҳамаи вазифаҳо',
    'analytics.completed': 'Иҷрошуда',
    'analytics.in_progress': 'Дар ҷараён',
    'analytics.overdue': 'Мӯҳлат гузашта',
    'analytics.for_selected_period': 'Барои давраи интихобшуда',
    'analytics.completion_rate': 'Фоизи иҷро: {rate}%',
    'analytics.active_tasks': 'Вазифаҳои фаъол',
    'analytics.require_attention': 'Диққат талаб мекунанд',
    'analytics.status_distribution': 'Тақсимот аз рӯи ҳолат',
    'analytics.status_distribution_desc': 'Миқдори умумии вазифаҳо аз рӯи ҳолат',
    'analytics.priority_distribution': 'Тақсимот аз рӯи аввалият',
    'analytics.priority_distribution_desc': 'Миқдори умумии вазифаҳо аз рӯи аввалият',
    'analytics.member_tasks': 'Вазифаҳои иштирокчӣ: {name}',
    'analytics.total_tasks_count': 'Ҳамаи вазифаҳо: {count}',
    'analytics.detailed_stats': 'Омори муфассал',
    'analytics.percentage_ratio': 'Нисбати фоизии вазифаҳо',
    'analytics.member_stats': 'Омор аз рӯи иштирокчиён',
    'analytics.member_stats_desc': 'Миқдори вазифаҳо барои ҳар иштирокчӣ',
    'analytics.activity_timeline': 'Фаъолият дар давра',
    'analytics.activity_timeline_desc': 'Эҷод ва иҷрои вазифаҳо аз рӯи вақт',
    'analytics.created': 'Эҷодшуда',
    'analytics.completed_tasks': 'Иҷрошуда',
    'analytics.tasks_count_suffix': 'вазифа',
    'analytics.chart_title': 'Диаграмма - Vazifa',
    'analytics.chart_analytics': 'Таҳлилоти Vazifa',

    // Tech Admin
    'tech_admin.title': 'Лавҳаи маъмури техникӣ',
    'tech_admin.subtitle': 'Назорати система ва амалиёти техникӣ',
    'tech_admin.load_error': 'Хатогии боркунии маълумот. Саҳифаро нав кунед.',

    // Статистика
    'tech_admin.total_users': 'Ҳамаи корбарон',
    'tech_admin.active_users': 'фаъол дар 30 рӯзи охирин',
    'tech_admin.new_today': 'нав имрӯз',
    'tech_admin.tasks': 'Вазифаҳо',
    'tech_admin.completed': 'иҷрошуда',
    'tech_admin.completion_rate': 'фоизи иҷро',
    'tech_admin.sms_delivery': 'Расонидани SMS',
    'tech_admin.failed': 'хатогӣ',
    'tech_admin.delivery_rate': 'фоизи расонидан',
    'tech_admin.system_status': 'Ҳолати система',
    'tech_admin.online': 'Онлайн',
    'tech_admin.offline': 'Офлайн',
    'tech_admin.uptime': 'Вақти кор',
    'tech_admin.environment': 'Муҳит',
    'tech_admin.today': 'имрӯз',

    // Пользователи по ролям
    'tech_admin.users_by_role': 'Корбарон аз рӯи нақш',
    'tech_admin.role_distribution': 'Тақсимоти нақшҳо',

    // SMPP статус
    'tech_admin.smpp_status': 'Ҳолати SMPP',
    'tech_admin.sms_gateway': 'Дарвозаи SMS',
    'tech_admin.connection': 'Пайвастшавӣ',
    'tech_admin.connected': 'Пайваст',
    'tech_admin.disconnected': 'Ҷудошуда',
    'tech_admin.reconnect_attempts': 'Кӯшишҳои аз нав пайвастшавӣ',
    'tech_admin.sms_today': 'SMS имрӯз',

    // Быстрые ссылки
    'tech_admin.user_management': 'Идоракунии корбарон',
    'tech_admin.user_management_desc': 'Дидан ва идора кардани корбарон',
    'tech_admin.sms_logs': 'Журналҳои SMS',
    'tech_admin.sms_logs_desc': 'Назорати расонидан ва таҳлили SMS',
    'tech_admin.email_logs': 'Журналҳои Email',
    'tech_admin.email_logs_desc': 'Назорати расонидан ва таҳлили Email',
    'tech_admin.queue_management': 'Идоракунии навбат',
    'tech_admin.queue_management_desc': 'Идоракунии навбати вазифаҳои SMS',
    'tech_admin.audit_logs': 'Журнали аудит',
    'tech_admin.audit_logs_desc': 'Пайгирии амалҳои маъмурон',
    'tech_admin.settings': 'Танзимот',
    'tech_admin.settings_desc': 'Танзими параметрҳои система',
    'tech_admin.system_health': 'Саломатии система',
    'tech_admin.system_health_desc': 'Метрикаҳои сервер ва назорат',

    // Страница пользователей
    'tech_admin.users.title': 'Идоракунии корбарон',
    'tech_admin.users.subtitle': 'Дидан ва идора кардани ҳамаи корбарони система',
    'tech_admin.users.search': 'Ҷустуҷӯ аз рӯи ном, email ё телефон...',
    'tech_admin.users.all_roles': 'Ҳамаи нақшҳо',
    'tech_admin.users.all_statuses': 'Ҳамаи ҳолатҳо',
    'tech_admin.users.active': 'Фаъол',
    'tech_admin.users.disabled': 'Ғайрифаъол',
    'tech_admin.users.create': 'Эҷоди корбар',
    'tech_admin.users.name': 'Ном',
    'tech_admin.users.email': 'Email',
    'tech_admin.users.phone': 'Телефон',
    'tech_admin.users.role': 'Нақш',
    'tech_admin.users.status': 'Ҳолат',
    'tech_admin.users.last_login': 'Вуруди охирин',
    'tech_admin.users.created': 'Эҷодшуда',
    'tech_admin.users.actions': 'Амалҳо',
    'tech_admin.users.edit': 'Таҳрир',
    'tech_admin.users.reset_password': 'Барқарори рамз',
    'tech_admin.users.disable': 'Ғайрифаъол кардан',
    'tech_admin.users.enable': 'Фаъол кардан',
    'tech_admin.users.delete': 'Нест кардан',
    'tech_admin.users.never': 'Ҳеҷ гоҳ',
    'tech_admin.users.no_users': 'Корбарон ёфт нашуданд',
    'tech_admin.users.loading': 'Боркунии корбарон...',
    'tech_admin.users.total': 'Ҳамагӣ',
    'tech_admin.users.page': 'Саҳифа',
    'tech_admin.users.of': 'аз',
    'tech_admin.users.prev': 'Қафо',
    'tech_admin.users.next': 'Пеш',

    // Создание/редактирование пользователя
    'tech_admin.users.create_title': 'Эҷоди корбар',
    'tech_admin.users.edit_title': 'Таҳрири корбар',
    'tech_admin.users.name_placeholder': 'Номро ворид кунед',
    'tech_admin.users.email_placeholder': 'Email-ро ворид кунед',
    'tech_admin.users.phone_placeholder': 'Телефонро ворид кунед',
    'tech_admin.users.password': 'Рамз',
    'tech_admin.users.password_placeholder': 'Рамзро ворид кунед',
    'tech_admin.users.select_role': 'Нақшро интихоб кунед',
    'tech_admin.users.creating': 'Эҷод шуда истодааст...',
    'tech_admin.users.saving': 'Захира шуда истодааст...',
    'tech_admin.users.save': 'Захира кардан',
    'tech_admin.users.cancel': 'Бекор кардан',

    // Сброс пароля
    'tech_admin.users.reset_password_title': 'Барқарори рамз',
    'tech_admin.users.new_password': 'Рамзи нав',
    'tech_admin.users.new_password_placeholder': 'Рамзи навро ворид кунед',
    'tech_admin.users.send_notification': 'Огоҳиномаи SMS фиристодан',
    'tech_admin.users.resetting': 'Барқарорӣ...',
    'tech_admin.users.reset': 'Барқарор кардани рамз',

    // Отключение пользователя
    'tech_admin.users.disable_title': 'Ғайрифаъол кардани корбар',
    'tech_admin.users.disable_confirm': 'Шумо мутмаин ҳастед, ки мехоҳед ин корбарро ғайрифаъол кунед?',
    'tech_admin.users.reason': 'Сабаб',
    'tech_admin.users.reason_placeholder': 'Сабабро ворид кунед',
    'tech_admin.users.disabling': 'Ғайрифаъол шуда истодааст...',

    // Удаление пользователя
    'tech_admin.users.delete_title': 'Нест кардани корбар',
    'tech_admin.users.delete_confirm': 'Шумо мутмаин ҳастед, ки мехоҳед ин корбарро нест кунед? Ин амал барнагардонданӣ аст.',
    'tech_admin.users.deleting': 'Нест шуда истодааст...',

    // SMS логи
    'tech_admin.sms.title': 'Журналҳои SMS',
    'tech_admin.sms.subtitle': 'Назорати фиристодани SMS ва таҳлил',
    'tech_admin.sms.search': 'Ҷустуҷӯ аз рӯи рақами телефон...',
    'tech_admin.sms.all_statuses': 'Ҳамаи ҳолатҳо',
    'tech_admin.sms.sent': 'Фиристода',
    'tech_admin.sms.pending': 'Интизорӣ',
    'tech_admin.sms.all_types': 'Ҳамаи намудҳо',
    'tech_admin.sms.phone': 'Телефон',
    'tech_admin.sms.message': 'Паём',
    'tech_admin.sms.type': 'Намуд',
    'tech_admin.sms.status': 'Ҳолат',
    'tech_admin.sms.date': 'Сана',
    'tech_admin.sms.actions': 'Амалҳо',
    'tech_admin.sms.resend': 'Аз нав фиристодан',
    'tech_admin.sms.no_logs': 'Журналҳои SMS ёфт нашуданд',
    'tech_admin.sms.loading': 'Боркунии журналҳои SMS...',
    'tech_admin.sms.total': 'Ҳамаи SMS',
    'tech_admin.sms.delivery_stats': 'Омори расонидан',
    'tech_admin.sms.error': 'Хатогӣ',
    'tech_admin.sms.otp': 'Рамзи OTP',
    'tech_admin.sms.password_reset': 'Барқарори рамз',
    'tech_admin.sms.task_notification': 'Огоҳиномаи вазифа',
    'tech_admin.sms.general': 'Умумӣ',

    // Email логи
    'tech_admin.email.title': 'Журналҳои Email',
    'tech_admin.email.subtitle': 'Назорати фиристодани Email ва таҳлил',
    'tech_admin.email.search': 'Ҷустуҷӯ аз рӯи email...',
    'tech_admin.email.recipient': 'Гиранда',
    'tech_admin.email.subject': 'Мавзӯъ',
    'tech_admin.email.type': 'Намуд',
    'tech_admin.email.status': 'Ҳолат',
    'tech_admin.email.date': 'Сана',
    'tech_admin.email.actions': 'Амалҳо',
    'tech_admin.email.resend': 'Аз нав фиристодан',
    'tech_admin.email.no_logs': 'Журналҳои Email ёфт нашуданд',
    'tech_admin.email.loading': 'Боркунии журналҳои Email...',
    'tech_admin.email.total': 'Ҳамаи Email',
    'tech_admin.email.delivery_stats': 'Омори расонидан',

    // Очередь
    'tech_admin.queue.title': 'Идоракунии навбат',
    'tech_admin.queue.subtitle': 'Назорат ва идоракунии навбати вазифаҳои SMS',
    'tech_admin.queue.waiting': 'Интизорӣ',
    'tech_admin.queue.active': 'Фаъол',
    'tech_admin.queue.completed': 'Анҷомёфта',
    'tech_admin.queue.failed': 'Хатогӣ',
    'tech_admin.queue.delayed': 'Ба таъхир',
    'tech_admin.queue.paused': 'Таваққуф',
    'tech_admin.queue.running': 'Кор мекунад',
    'tech_admin.queue.pause': 'Таваққуф кардан',
    'tech_admin.queue.resume': 'Идома додан',
    'tech_admin.queue.clean': 'Тоза кардани кӯҳна',
    'tech_admin.queue.job_id': 'ID вазифа',
    'tech_admin.queue.job_name': 'Ном',
    'tech_admin.queue.job_data': 'Маълумот',
    'tech_admin.queue.job_status': 'Ҳолат',
    'tech_admin.queue.job_attempts': 'Кӯшишҳо',
    'tech_admin.queue.job_created': 'Эҷодшуда',
    'tech_admin.queue.job_actions': 'Амалҳо',
    'tech_admin.queue.retry': 'Такрор кардан',
    'tech_admin.queue.remove': 'Нест кардан',
    'tech_admin.queue.no_jobs': 'Вазифаҳо ёфт нашуданд',
    'tech_admin.queue.loading': 'Боркунии навбат...',
    'tech_admin.queue.stats': 'Омори навбат',

    // Аудит логи
    'tech_admin.audit.title': 'Журнали аудит',
    'tech_admin.audit.subtitle': 'Пайгирии ҳамаи амалҳои маъмурон',
    'tech_admin.audit.search': 'Ҷустуҷӯ аз рӯи тавсиф...',
    'tech_admin.audit.all_actions': 'Ҳамаи амалҳо',
    'tech_admin.audit.all_categories': 'Ҳамаи категорияҳо',
    'tech_admin.audit.actor': 'Корбар',
    'tech_admin.audit.action': 'Амал',
    'tech_admin.audit.category': 'Категория',
    'tech_admin.audit.target': 'Ҳадаф',
    'tech_admin.audit.description': 'Тавсиф',
    'tech_admin.audit.ip': 'Суроғаи IP',
    'tech_admin.audit.date': 'Сана',
    'tech_admin.audit.status': 'Ҳолат',
    'tech_admin.audit.success': 'Муваффақ',
    'tech_admin.audit.error': 'Хатогӣ',
    'tech_admin.audit.details': 'Тафсилот',
    'tech_admin.audit.no_logs': 'Сабтҳои аудит ёфт нашуданд',
    'tech_admin.audit.loading': 'Боркунии журнали аудит...',
    'tech_admin.audit.user': 'Корбар',
    'tech_admin.audit.task': 'Вазифа',
    'tech_admin.audit.system': 'Система',
    'tech_admin.audit.sms': 'SMS',
    'tech_admin.audit.email': 'Email',

    // Настройки
    'tech_admin.settings.title': 'Танзимоти система',
    'tech_admin.settings.subtitle': 'Танзими параметрҳои система',
    'tech_admin.settings.sms_settings': 'Танзимоти SMS',
    'tech_admin.settings.email_settings': 'Танзимоти Email',
    'tech_admin.settings.notification_settings': 'Танзимоти огоҳиномаҳо',
    'tech_admin.settings.maintenance': 'Режими хизматрасонӣ',
    'tech_admin.settings.security': 'Амният',
    'tech_admin.settings.enabled': 'Фаъол',
    'tech_admin.settings.disabled': 'Ғайрифаъол',
    'tech_admin.settings.retry_attempts': 'Миқдори кӯшишҳо',
    'tech_admin.settings.retry_delay': 'Таъхир байни кӯшишҳо (мс)',
    'tech_admin.settings.daily_limit': 'Лимити рӯзона',
    'tech_admin.settings.task_assignment': 'Таъини вазифа',
    'tech_admin.settings.task_completion': 'Анҷоми вазифа',
    'tech_admin.settings.task_reminder': 'Ёдоварии вазифа',
    'tech_admin.settings.password_reset': 'Барқарори рамз',
    'tech_admin.settings.maintenance_mode': 'Режими хизматрасонӣ',
    'tech_admin.settings.maintenance_message': 'Паёми хизматрасонӣ',
    'tech_admin.settings.max_login_attempts': 'Ҳадди аксари кӯшишҳои вуруд',
    'tech_admin.settings.lockout_duration': 'Давомнокии қулфшавӣ (дақ)',
    'tech_admin.settings.session_timeout': 'Таймаути сессия (дақ)',
    'tech_admin.settings.two_factor': 'Аутентификатсияи дуомила',
    'tech_admin.settings.save': 'Захираи танзимот',
    'tech_admin.settings.saving': 'Захира шуда истодааст...',
    'tech_admin.settings.saved': 'Танзимот захира шуд',
    'tech_admin.settings.loading': 'Боркунии танзимот...',

    // Система
    'tech_admin.system.title': 'Саломатии система',
    'tech_admin.system.subtitle': 'Назорати ҳолати сервер ва хидматҳо',
    'tech_admin.system.server': 'Сервер',
    'tech_admin.system.server_uptime': 'Вақти кор',
    'tech_admin.system.server_version': 'Версияи Node.js',
    'tech_admin.system.server_platform': 'Платформа',
    'tech_admin.system.server_arch': 'Архитектура',
    'tech_admin.system.database': 'Базаи маълумот',
    'tech_admin.system.db_status': 'Ҳолат',
    'tech_admin.system.db_response': 'Вақти ҷавоб',
    'tech_admin.system.smpp': 'Дарвозаи SMPP',
    'tech_admin.system.smpp_status': 'Ҳолат',
    'tech_admin.system.smpp_host': 'Хост',
    'tech_admin.system.smpp_port': 'Порт',
    'tech_admin.system.smpp_reconnect': 'Аз нав пайваст кардан',
    'tech_admin.system.memory': 'Хотира',
    'tech_admin.system.memory_total': 'Ҳамагӣ',
    'tech_admin.system.memory_free': 'Озод',
    'tech_admin.system.memory_used': 'Истифодашуда',
    'tech_admin.system.cpu': 'Протсессор',
    'tech_admin.system.cpu_cores': 'Ядраҳо',
    'tech_admin.system.cpu_model': 'Модел',
    'tech_admin.system.cpu_load': 'Борӣ',
    'tech_admin.system.process': 'Протсесс',
    'tech_admin.system.heap_used': 'Heap истифодашуда',
    'tech_admin.system.heap_total': 'Heap ҳамагӣ',
    'tech_admin.system.rss': 'RSS',
    'tech_admin.system.collections': 'Коллексияҳои БД',
    'tech_admin.system.collection_name': 'Ном',
    'tech_admin.system.collection_docs': 'Ҳуҷҷатҳо',
    'tech_admin.system.collection_size': 'Андоза',
    'tech_admin.system.collection_indexes': 'Индексҳо',
    'tech_admin.system.loading': 'Боркунии маълумоти система...',
    'tech_admin.system.refresh': 'Навсозӣ',
    'tech_admin.system.reconnecting': 'Аз нав пайвастшавӣ...',
    'tech_admin.system.ms': 'мс',

    // Ошибки
    'errors.generic': 'Хатогӣ рух дод',
    'errors.network': 'Хатогии шабака',
    'errors.unauthorized': 'Дастрасӣ нест',
    'errors.not_found': 'Ёфт нашуд',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>('ru');

  // Загрузить язык из localStorage при инициализации
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && (savedLanguage === 'ru' || savedLanguage === 'tj')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
